#!/usr/bin/env python3

import os
import sys
from helpers import *

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    try:
        # get user tweets
        tweets = get_user_timeline(sys.argv[1])

        # analyze tweets
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(str(tweet), "green"))
            elif score < 0.0:
                print(colored(str(tweet), "red"))
            else:
                print(colored(str(tweet), "yellow"))

    except:
        sys.exit(1);

if __name__ == "__main__":
    main()